### ISSUE TITLE
社名のフォントが大きいので、小さくする。

### ISSUE THREAD

**Issue by ogom** [rubykansai/osaka03#36]
社名のフォントが大きいので、小さくする。
![image](https://github.com/rubykansai/osaka03/assets/471923/774f232c-0407-45c3-b4c0-2f778197afac)

これくらいのバランスがよいです。
![image](https://github.com/rubykansai/osaka03/assets/471923/731d8951-217a-4923-9d5c-a7b3dad5be3c)

**Comment by ydah** [comment]
@ogom すみません再現しなかったのですが、どの幅で見れば再現するでしょうか。
![スクリーンショット 2023-08-24 10 51 44](https://github.com/rubykansai/osaka03/assets/13041216/60300eb4-0c4a-49a6-8108-174928e0b46c)
![スクリーンショット 2023-08-24 10 52 33](https://github.com/rubykansai/osaka03/assets/13041216/d2146b14-96d7-4f78-bfdd-572ec0db209b)
![スクリーンショット 2023-08-24 10 52 49](https://github.com/rubykansai/osaka03/assets/13041216/02967ad8-b34c-4bc8-b8bf-32c7cdc330a6)

**Comment by ogom** [comment]
@ydah 
すみません。こちらでも再現しなくなりました。2回目のリリースをしたからかもしれません。クローズします。

**Comment by ydah** [comment]
@ogom ご確認いただきありがとうございます :bow:
